name: Build and Publish
on: [push]
jobs:
  diff:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew decompileVineflower decompileTargetVineflower --stacktrace
      - name: Check Target Decompiled
        id: can-create-diff
        uses: andstor/file-existence-action@v3
        with:
          files: "namedTargetSrc/net/minecraft/client/main/Main.java"
      - name: Create diff
        if: ${{ steps.can-create-diff.outputs.files_exists == 'true' }}
        run: diff -bur namedTargetSrc/ namedSrc/ > target.diff
        continue-on-error: true
      - name: Create diff comment
        uses: ./.github/actions/diff/
        if: ${{ matrix.java == 21 }}
        id: diff
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-src-exists: ${{ steps.can-create-diff.outputs.files_exists }}
      - name: Upload diff
        if: hashFiles('target.diff') != ''
        uses: actions/upload-artifact@v3
        with:
          name: Diff
          path: target.diff


  publish:
    if: ${{ github.repository_owner == 'BookkeepersMC' }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root

    steps:
      - run: apt update && apt install git -y && git --version
      - run: git config --global --add safe.directory /__w/book/book
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/checkout@v4
        with:
          repository: "BookkeepersMC/m2"
          ref: master
          path: "./m2/"
          token: ${{ secrets.GIT_PAT }}

      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
          prefix: "build/${{ github.ref }}"

      - run: ./gradlew build javadocJar
      - name: Build artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
      - run: ./gradlew javadoc publish --stacktrace
        env:
          BRANCH_NAME: ${{ github.ref }}

      - name: Commit to m2
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "./com/"
          cwd: "./m2/"
          default_author: github_actions
          message: "Publish book mappings"
