name: Release
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: gradle/actions/wrapper-validation@v3
      - run: ./gradlew build javadocJar --stacktrace
      - name: Build artifacts
        if: ${{ matrix.java == 21 }}
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
  publish:
    if: ${{ github.repository_owner == 'BookkeepersMC' }}
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21
      options: --user root

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/checkout@v4
        with:
          repository: "BookkeepersMC/m2"
          ref: master
          path: "./m2/"
          token: ${{ secrets.GIT_PAT }}

      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
          prefix: "build/${{ github.ref }}"

      - run: ./gradlew build javadoc javadocJar publish --stacktrace
        env:
          BRANCH_NAME: ${{ github.ref }}

      - name: Commit to m2
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: "./com/"
          cwd: "./m2/"
          default_author: github_actions
          message: "Publish book mappings"
